version: "3"
services:
  web:
    image: "restweb:latest"
    ports:
      - "3001:80"

  api:
    image: "restapi:latest"
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_URI=mongodb://root:1234@mongo/rest?authSource=admin
      - MONGODB_DEBUG=false
      - DEBUG=*,-express:*,-morgan,-send,-body-parser:*
      - WEB_URL=http://localhost:3001
      - SENTRY_DNS=
      - SMTP_HOST=
      - SMTP_PORT=
      - SMTP_USER=
      - SMTP_PWD=

  mongo:
    image: "mongo:4.2.3-bionic"
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
    volumes:
      - mongo-data:/data/db
      - ./scripts/db:/scripts

volumes:
  mongo-data:
