version: '3'
services:
  web:
    build: .
    ports:
      - "8087:3000"
    environment:
      - DB_URI=mongodb://mymongo/blog
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=465
      - SMTP_USER=lam.huynh@magento.codespot.vn
      - SMTP_PWD=!H4Xwz]S
      - NODE_ENV=production
      - PORT=3000
      - WEB_URL=http://localhost:3001
      - SENTRY_DNS=https://1f4bf702246d45d28e4f0d24d17832ca:0679e0a6c0804c19924078f98954f638@sentry.io/264486
      - MONGODB_DEBUG=false
      - DEBUG=*,-express:*,-morgan,-send,-body-parser:*
  mymongo:
    image: "mongo:3.4.10"
    ports:
      - "8086:27017"
    volumes:
     - ./mongo:/data/db
     - ./data:/scripts
